### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by The-Mach34** [X9VoiD/vmulti-bin#1]
I'm unsure as to how I should install the driver.zip's contents into OpenTabletDriver in order to use the WindowsInk mode. I tried copying all of the zip's contents into the plugin folder like I did with the other plugins and tools but that just made all of OpenTabletDriver just crash every time I tried to open if. When I removed those files from the plugins it fixed but it never installed VMulti or WondowsInk.

**Comment by skyborgff** [comment]
You have to go to the ReleASES https://github.com/X9VoiD/vmulti-bin/releases/tag/v1.0 and download the zip, extract and install

**Comment by The-Mach34** [comment]
Oh, I figured it out. Thanks.
