### ISSUE TITLE
vmulti.inf.devcon.exe failed

### ISSUE THREAD

**Issue by judopudo** [X9VoiD/vmulti-bin#11]
<img width="674" alt="Skjermbilde 2024-03-05 152909" src="https://github.com/X9VoiD/vmulti-bin/assets/162336881/0097f921-004a-44c2-b0f2-340babc7fd85">

I'm on a cheap Acer Aspire arm64 laptop with windows 11. The Wacom windows driver was not supported by the operating system, pressumably because of the arm architechture. I was hoping that open tablet driver would allow me to use my Wacom One tablet, but as you see I get an error message when trying to install vmulti.

**Comment by X9VoiD** [comment]
This is a pre-built VMulti that only supports x86_64. Unfortunately this cannot be fixed.

**Comment by Ianothebob** [comment]
Could you possibly supply us with source code or which descriptors you modified in order to compile it on our arm64 systems?
