### ISSUE TITLE
can't install the driver

### ISSUE THREAD

**Issue by hammam12345** [X9VoiD/vmulti-bin#4]
I installed the driver but it doesn't show in the diagnostics and it  crashes whenever i use the mod
![image](https://user-images.githubusercontent.com/40491516/140566568-0b27de7f-bfa7-4cde-9d1a-ca5fe8f37a90.png)
Update: when i run OTD as an administrator it works perfectly but as i heard its not good to run OTD as an administrator

**Comment by X9VoiD** [comment]
As what has been said in the installation instructions:
![image](https://user-images.githubusercontent.com/10338031/142736099-afad5bd2-7fc8-4051-9bee-ad77f12d4fd5.png)
